version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm pkg delete scripts.prepare
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync --delete ./dist/kognito/browser s3://${DEPLOY_BUCKET}
      - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths /index.html
